name: "Bug report"
description: Judicator is not working as expected? Create a report!
labels: [bug]
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to fill out this bug report.
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is. 
    placeholder: What happened? Also tell us, what did you expect to happen?
  validations:
      required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: "Steps to reproduce the behavior:"
    placeholder: Describe required actions to reproduce the bug.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: .
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
